url:                http://jacob.mc-donald.me
title: 				Jacob McDonald
baseurl: 			''
permalink: 			/:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->'

email: 				jmc734@gmail.com
twitter_username: 	jacob_mcdonald
github_username:  	jmc734

safe: 				true
lsi: 				false
markdown: 			kramdown
highlighter: 		pygments

exclude: 			['build_archive']
